// <auto-generated />
using System;
using BlazorEcommerce.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorEcommerce.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240307014347_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fas fa-spa",
                            Name = "Beleza"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fas fa-couch",
                            Name = "Moveis"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fas fa-headphones",
                            Name = "Eletronicos"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fas fa-shoe-prints",
                            Name = "Calcados"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100,
                            CategoryId = 1,
                            Description = "Um kit fornecido pela Natura, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza1.png",
                            Name = "Glossier - Beleza Kit",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 45,
                            CategoryId = 1,
                            Description = "Um kit fornecido pela Curology, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza2.png",
                            Name = "Curology - Kit para Pele",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 30,
                            CategoryId = 1,
                            Description = "Um kit fornecido pela Glossier, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza3.png",
                            Name = "Óleo de Coco Orgânico",
                            Price = 20m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 60,
                            CategoryId = 1,
                            Description = "Um kit fornecido pela Curology, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza4.png",
                            Name = "Schwarzkopf - Kit de cuidados com a pele e cabelo",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 85,
                            CategoryId = 1,
                            Description = "Kit de cuidados com a pele, contendo produtos para cuidados com a pele e cabelos",
                            ImageUrl = "/Imagens/Beleza/Beleza5.png",
                            Name = "Kit de cuidados com a pele",
                            Price = 30m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 120,
                            CategoryId = 3,
                            Description = "Air Pods - fones de ouvido sem fio intra-auriculares",
                            ImageUrl = "/Imagens/Eletronicos/eletronico1.png",
                            Name = "Fones de ouvidos",
                            Price = 100m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200,
                            CategoryId = 3,
                            Description = "Fones de ouvido dourados na orelha - esses fones de ouvido não são sem fio",
                            ImageUrl = "/Imagens/Eletronicos/eletronico2.png",
                            Name = "Fones de ouvido dourados",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8,
                            Amount = 300,
                            CategoryId = 3,
                            Description = "Fones de ouvido pretos na orelha - esses fones de ouvido não são sem fio",
                            ImageUrl = "/Imagens/Eletronicos/eletronico3.png",
                            Name = "Fones de ouvido pretos",
                            Price = 40m
                        },
                        new
                        {
                            Id = 9,
                            Amount = 20,
                            CategoryId = 3,
                            Description = "Câmera Digital Sennheiser - Câmera digital de alta qualidade fornecida pela Sennheiser - inclui tripé",
                            ImageUrl = "/Imagens/Eletronicos/eletronico4.png",
                            Name = "Câmera digital Sennheiser com tripé",
                            Price = 600m
                        },
                        new
                        {
                            Id = 10,
                            Amount = 15,
                            CategoryId = 3,
                            Description = "Canon Digital Camera - Câmera digital de alta qualidade fornecida pela Canon",
                            ImageUrl = "/Imagens/Eletronicos/eletronico5.png",
                            Name = "Câmera Digital Canon",
                            Price = 500m
                        },
                        new
                        {
                            Id = 11,
                            Amount = 60,
                            CategoryId = 3,
                            Description = "Gameboy - Fornecido por Nintendo",
                            ImageUrl = "/Imagens/Eletronicos/tecnologia6.png",
                            Name = "Nintendo Gameboy",
                            Price = 100m
                        },
                        new
                        {
                            Id = 12,
                            Amount = 212,
                            CategoryId = 2,
                            Description = "Cadeira de escritório em couro preto muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis1.png",
                            Name = "Cadeira de escritório de couro preto",
                            Price = 50m
                        },
                        new
                        {
                            Id = 13,
                            Amount = 112,
                            CategoryId = 2,
                            Description = "Cadeira de escritório em couro rosa muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis2.png",
                            Name = "Cadeira de escritório de couro rosa",
                            Price = 50m
                        },
                        new
                        {
                            Id = 14,
                            Amount = 90,
                            CategoryId = 2,
                            Description = "Poltrona muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis3.png",
                            Name = "Espreguiçadeira",
                            Price = 70m
                        },
                        new
                        {
                            Id = 15,
                            Amount = 95,
                            CategoryId = 2,
                            Description = "Poltrona prateada muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis4.png",
                            Name = "Silver Lounge Chair",
                            Price = 120m
                        },
                        new
                        {
                            Id = 16,
                            Amount = 100,
                            CategoryId = 2,
                            Description = "Abajur de mesa de porcelana branco e azul",
                            ImageUrl = "/Imagens/Moveis/moveis6.png",
                            Name = "Luminária de mesa de porcelana",
                            Price = 15m
                        },
                        new
                        {
                            Id = 17,
                            Amount = 73,
                            CategoryId = 2,
                            Description = "Abajur de mesa de escritório",
                            ImageUrl = "/Imagens/Moveis/moveis7.png",
                            Name = "Office Table Lamp",
                            Price = 20m
                        },
                        new
                        {
                            Id = 18,
                            Amount = 50,
                            CategoryId = 4,
                            Description = "Tênis Puma confortáveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado1.png",
                            Name = "Tênis Puma",
                            Price = 100m
                        },
                        new
                        {
                            Id = 19,
                            Amount = 60,
                            CategoryId = 4,
                            Description = "Tênis coloridos - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado2.png",
                            Name = "Tênis Colodiros",
                            Price = 150m
                        },
                        new
                        {
                            Id = 20,
                            Amount = 70,
                            CategoryId = 4,
                            Description = "Tênis Nike azul - disponível na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado3.png",
                            Name = "Tênis Nike Azul",
                            Price = 200m
                        },
                        new
                        {
                            Id = 21,
                            Amount = 120,
                            CategoryId = 4,
                            Description = "Treinadores Hummel coloridos - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado4.png",
                            Name = "Tênis Hummel Coloridos",
                            Price = 120m
                        },
                        new
                        {
                            Id = 22,
                            Amount = 100,
                            CategoryId = 4,
                            Description = "Tênis Nike vermelho - disponível na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado5.png",
                            Name = "Tênis Nike Vermelho",
                            Price = 200m
                        },
                        new
                        {
                            Id = 23,
                            Amount = 150,
                            CategoryId = 4,
                            Description = "Sandálias Birkenstock - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado6.png",
                            Name = "Sandálidas Birkenstock",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.CartItem", b =>
                {
                    b.HasOne("BlazorEcommerce.Api.Entities.Cart", "Cart")
                        .WithMany("Itens")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorEcommerce.Api.Entities.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Product", b =>
                {
                    b.HasOne("BlazorEcommerce.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.User", b =>
                {
                    b.HasOne("BlazorEcommerce.Api.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Cart", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BlazorEcommerce.Api.Entities.Product", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
